## Numpy array
Learn about Numpy Library

In [1]:
import numpy as np

### Creating array from List

In [2]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3],[1,5,9]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [1 5 9]]


### List vs Numpy array

In [6]:
py_list = [1,2,3]
print("Python list multiplication", py_list * 10)

np_array = np.array([1,2,3]) #Element wise multiplication
print("Python array multiplication", np_array * 10)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) *2
print("\n Numpy operation time: ", time.time() - start)


Python list multiplication [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
Python array multiplication [10 20 30]

 List operation time:  0.13643813133239746

 Numpy operation time:  0.0074193477630615234


### Creating array from scratch

In [14]:
zeroes = np.zeros((3,4))
print("Zero's Array: \n", zeroes)

ones = np.ones((2,3))
print("One's Array: \n", ones)

full = np.full((2,4),5)
print("Full Array: \n", full)

random = np.random.random((5,9))
print("Random Array: \n", random)

sequence = np.arange(1,11,2)
print("Sequence Array: \n", sequence)

Zero's Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One's Array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array: 
 [[5 5 5 5]
 [5 5 5 5]]
Random Array: 
 [[0.88874149 0.33674521 0.67590889 0.00181895 0.16472123 0.98114013
  0.67834086 0.42429084 0.17126909]
 [0.11705113 0.49745806 0.81825944 0.21322972 0.40819653 0.13535006
  0.16694186 0.43662728 0.60158565]
 [0.92263039 0.31436482 0.77955833 0.68459757 0.31109714 0.13402708
  0.43939215 0.92124169 0.97448232]
 [0.56731685 0.05177478 0.02075065 0.5334611  0.06012348 0.37408272
  0.46965689 0.2294282  0.51433824]
 [0.75178672 0.68550475 0.48192904 0.935056   0.7420007  0.35259314
  0.53257052 0.83340811 0.64014085]]
Sequence Array: 
 [1 3 5 7 9]


### Vector, Matrix & Tensor

In [ ]:
vector = np.array([1,2,3,4,5])
print("Vector: \n",vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix: \n",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor: \n",tensor)


Vector: 
 [1 2 3 4 5]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [22]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape :", arr.shape)
print("Dimension :", arr.ndim)
print("Size :", arr.size)
print("DType :", arr.dtype)

Shape : (2, 3)
Dimension : 2
Size : 6
DType : int64


### Array Reshaping

In [39]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened Array: ", flattened)

# ravel (return view instead of copy)
raveled = reshaped.ravel()
print("\n Raveled Array: ", raveled)

#Transpose
transpose = reshaped.T
print("\n Transpose array ", transpose)


Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
