# Numpy Array Operations

In [1]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Slicing:", arr[2:9])
print("With Steps", arr[1:8:2])
print("Negavtive indexing", arr[-2])

Slicing: [3 4 5 6 7 8 9]
With Steps [2 4 6 8]
Negavtive indexing 9


In [10]:
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print("Specific element", arr_2d[1,2])
print("Entire Row", arr_2d[0])
print("Entire Column", arr_2d[:,1])


Specific element 6
Entire Row [1 2 3]
Entire Column [2 5 8]


## Sorting

In [14]:
unsorted = np.array([3,4,1,8,9,6,7,5,2])
print("Sorted Array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1], [1,2], [2,3]])
print("Sorted 2D array by coloumn", np.sort(arr_2d_unsorted, axis=0))

Sorted Array:  [1 2 3 4 5 6 7 8 9]
Sorted 2D array by coloumn [[1 1]
 [2 2]
 [3 3]]


## Filter

In [16]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers", even_numbers)


Even numbers [ 2  4  6  8 10]


## Filter with mask

In [17]:
mask = numbers > 5
print("Number greater than 5", numbers[mask])

Number greater than 5 [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [18]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [20]:
condition_array = np.where(numbers > 5, numbers*4, numbers)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


### Adding and removing data

In [21]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


### Array Compatibility

In [23]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([1,2,3])

print("Compatibility shapes: ", a.shape == b.shape)

Compatibility shapes:  False


In [27]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))
print(original,"\n")
print("With new row",with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original, new_col))
print("With new column", with_new_col)

[[1 2]
 [3 4]] 

With new row [[1 2]
 [3 4]
 [5 6]]
With new column [[1 2 7]
 [3 4 8]]


In [28]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("Array after deletion: ",deleted)

Array after deletion:  [1 2 4 5]
